builds:
  - id: catd
    main: .
    flags: "-tags netgo"
    ldflags:
      - -w -s
      - -X main.MetadataVersion={{.Version}}
      - -X main.MetadataCommit={{.FullCommit}}
      - -X main.MetadataMTime={{.Date}}
      - -extldflags "-static"
      - -s -extldflags "-sectcreate __TEXT __info_plist Info.plist"
    binary: catd
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
release:
  disable: true
archives:
  - format: binary
